steps:
  - label: 'Pre-Build'
    command: .buildkite/scripts/lifecycle/pre_build.sh
    agents:
      queue: kibana-default

  - wait

  - label: 'Build Kibana Distribution and Plugins'
    command: .buildkite/scripts/steps/build_kibana.sh
    agents:
      queue: c2-16
    key: build
    if: "build.env('KIBANA_BUILD_ID') == null || build.env('KIBANA_BUILD_ID') == ''"

  - label: 'Run Performance Tests'
    command: .buildkite/scripts/steps/functional/run_performance_journeys.sh
    agents:
      queue: n2-2
    depends_on: build
    key: tests
    timeout_in_minutes: 60

  - label: 'Performance Tests dataset extraction for scalability benchmarking'
    command: .buildkite/scripts/steps/functional/scalability_dataset_extraction.sh
    agents:
      queue: n2-2
    depends_on: tests

  - label: 'Report performance metrics to ci-stats'
    command: .buildkite/scripts/steps/functional/report_performance_metrics.sh
    agents:
      queue: n2-2
    depends_on: tests

  - wait: ~
    continue_on_failure: true

  - label: 'Post-Build'
    command: .buildkite/scripts/lifecycle/post_build.sh
    agents:
      queue: kibana-default
